### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by alfrekjv** [sehrope/node-rand-token#10]
I am getting the following error when running my app on a CentOS 7 server.

Code for line 23 of users.js is as follows:

```javascript:
let salt = randtoken.generate(16)
```

```
0|server   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|server   | TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
0|server   |     at randomBytes (internal/crypto/random.js:44:11)
0|server   |     at Object.options.source (/root/facturas-api/node_modules/rand-token/index.js:61:18)
0|server   |     at Object.generate (/root/facturas-api/node_modules/rand-token/index.js:96:29)
0|server   |     at signup (/root/facturas-api/controllers/users.js:23:38)
```

Any ideas?

**Update:** Node Version is v9.3.0 (on v8.5.0 works like a charm)

**Comment by sehrope** [comment]
This is resolved by upgrading to the latest version of rand-token. It's due to a change in Node v9. See the recently closed issues for details.

**Comment by alfrekjv** [comment]
Thank you @sehrope!
